### PR TITLE
Add pin names to binary information

### PR DESCRIPTION
**Pull request by fduxiao**
I added the pin names to the binary information in case someone downloaded the firmware ten years ago and forget which pins to use.

### CODE REVIEW

**Comment by P33M** [comment]
Can you update this PR on top of master and add UART_CTS as well?

**Comment by fduxiao** [comment]
@P33M done as you wish. I also added baud rate and interface to features. Now the output looks like

```shell
$ picotool info debugprobe.uf2 -a
File debugprobe.uf2:

Program Information
 name:          debugprobe
 features:      PROBE UART BAUDRATE 115200
                PROBE UART INTERFACE uart1
                UART stdin / stdout
 binary start:  0x10000000
 binary end:    0x1000a2d8

Fixed Pin Information
 0:   UART0 TX, UART0 TX
 1:   UART0 RX
 4:   PROBE UART TX
 5:   PROBE UART RX
 12:  PROBE SWCLK
 13:  PROBE SWDI
 14:  PROBE SWDIO
 25:  LED

Build Information
 sdk version:       1.5.1
 pico_board:        pico
 boot2_name:        boot2_w25q080
 build date:        Mar 18 2024
 build attributes:  Release
```

Besides, I notice a naming difference in [include/board_example_config.h](https://github.com/raspberrypi/debugprobe/blob/c0ff91421a32df23aa3cd02cefe1850748e0e7bb/include/board_example_config.h#L63).
```C
/* PIO config for PROBE_IO_OEN - note that SWDIOEN and SWCLK are both side_set signals, so must be consecutive. */
#if defined(PROBE_IO_SWDIOEN)
#define PROBE_PIN_SWDIOEN (PROBE_PIN_OFFSET + 0)
#define PROBE_PIN_SWCLK (PROBE_PIN_OFFSET + 1)
#define PROBE_PIN_SWDIO (PROBE_PIN_OFFSET + 2)
#define PROBE_PIN_SWDI (PROBE_PIN_OFFSET + 3)
#endif
```

See the difference between `PROBE_IO_SWDIOEN` and `PROBE_IO_OEN`. Is this a mistake? I can open another pull request for it.

**Comment by P33M** [comment]
The compile guard is wrong - it should be PROBE_IO_OEN. Please add another commit to this PR which fixes the typo.

**Comment by fduxiao** [comment]
@P33M Fixed.

**Comment by P33M** [comment]
Thanks, applied.

**Comment by P33M** [comment]
Hi, a question arose in #145 - the `probe_config.c` file you added is missing a license header. Could you reply to confirm that
a) this PR is your own work and
b) you are willing to grant a permissive open-source licence to this file (BSD 3-clause preferred)?

Thanks

**Comment by fduxiao** [comment]
@P33M I confirm that the PR is my own work and I grant the open-source license to this file.

**Pull request merged**
